from __future__ import annotations

from .models import ComplianceRule


def _rule(
    rule_id: str,
    title: str,
    category: str,
    severity: str,
    controls: tuple[str, ...],
    evidence_sources: tuple[str, ...],
    remediation: str,
    description: str = "",
) -> ComplianceRule:
    return ComplianceRule(rule_id, title, category, severity, controls, evidence_sources, remediation, description)


RULES: tuple[ComplianceRule, ...] = (
    _rule(
        "L26-ACCESS-001",
        "Local-81 access policy is configured",
        "access",
        "high",
        ("NIST_SP_800_53:AC-3", "NIST_SP_800_53:AC-6", "CMS_ARS:AC-3", "CMS_ARS:AC-6"),
        (".local81/config.ini [access]",),
        "Configure explicit allowed users or groups, deny root where practical, and deny remote command steps by default.",
    ),
    _rule(
        "L26-SEC-001",
        "Secrets are not stored inline",
        "config",
        "critical",
        ("NIST_SP_800_53:IA-5", "NIST_SP_800_53:SC-28", "CMS_ARS:IA-5", "CMS_ARS:SC-28"),
        (".local81/config.ini", ".local81/config.yaml", "package and environment files"),
        "Replace literal secrets with environment variable names, external references, or protected files.",
    ),
    _rule(
        "L26-LNX-INV-001",
        "Linux OS inventory is available",
        "linux",
        "info",
        ("NIST_SP_800_53:CM-8", "NIST_SP_800_53:CM-2", "CMS_ARS:CM-8", "CMS_ARS:CM-2"),
        ("/etc/os-release", "uname", "package manager metadata"),
        "Record OS, kernel, package manager, and service manager baseline evidence.",
    ),
    _rule(
        "L26-LNX-FS-001",
        "Critical system files use restrictive ownership and permissions",
        "linux",
        "high",
        ("NIST_SP_800_53:AC-6", "NIST_SP_800_53:CM-6", "CMS_ARS:AC-6", "CMS_ARS:CM-6"),
        ("/etc/passwd", "/etc/shadow", "/etc/sudoers", "/etc/ssh/sshd_config"),
        "Keep sensitive system files root-owned and not writable by group or other users.",
    ),
    _rule(
        "L26-LNX-FS-002",
        "World-writable temporary directories use sticky bit",
        "linux",
        "medium",
        ("NIST_SP_800_53:CM-6", "NIST_SP_800_53:SI-7", "CMS_ARS:CM-6", "CMS_ARS:SI-7"),
        ("/tmp", "/var/tmp", "/dev/shm"),
        "Add sticky bit or restrict permissions on shared writable directories.",
    ),
    _rule(
        "L26-LNX-MNT-001",
        "Temporary mounts use nodev nosuid noexec where compatible",
        "linux",
        "medium",
        ("NIST_SP_800_53:CM-6", "NIST_SP_800_53:SC-7", "CMS_ARS:CM-6", "CMS_ARS:SC-7"),
        ("/etc/fstab", "/proc/self/mountinfo"),
        "Apply nodev,nosuid,noexec to /tmp, /var/tmp, and /dev/shm unless an approved exception exists.",
    ),
    _rule(
        "L26-LNX-SYSCTL-001",
        "IP forwarding is disabled unless approved",
        "linux",
        "high",
        ("NIST_SP_800_53:SC-7", "NIST_SP_800_53:AC-4", "CMS_ARS:SC-7", "CMS_ARS:AC-4"),
        ("/proc/sys/net/ipv4/ip_forward", "/proc/sys/net/ipv6/conf/all/forwarding", "/etc/sysctl*"),
        "Persist IP forwarding disabled or document the host as an approved router.",
    ),
    _rule(
        "L26-LNX-SYSCTL-002",
        "Source routing and ICMP redirects are disabled",
        "linux",
        "high",
        ("NIST_SP_800_53:SC-7", "NIST_SP_800_53:CM-6", "CMS_ARS:SC-7", "CMS_ARS:CM-6"),
        ("/proc/sys/net/ipv4/conf/*", "/etc/sysctl*"),
        "Disable accept_source_route, accept_redirects, and secure_redirects in runtime and persistent sysctl settings.",
    ),
    _rule(
        "L26-LNX-SYSCTL-004",
        "Kernel exploit-hardening settings are enabled",
        "linux",
        "medium",
        ("NIST_SP_800_53:CM-6", "NIST_SP_800_53:SI-7", "CMS_ARS:CM-6", "CMS_ARS:SI-7"),
        ("/proc/sys/kernel/randomize_va_space", "/proc/sys/kernel/yama/ptrace_scope", "/etc/sysctl*"),
        "Enable ASLR, restrict ptrace where compatible, and restrict or disable core dumps in production.",
    ),
    _rule(
        "L26-LNX-NET-001",
        "Host firewall posture is documented",
        "linux",
        "high",
        ("NIST_SP_800_53:SC-7", "NIST_SP_800_53:CM-7", "CMS_ARS:SC-7", "CMS_ARS:CM-7"),
        ("nftables", "iptables", "ufw", "firewalld"),
        "Use default-deny inbound policy with explicit allow rules and documented exceptions.",
    ),
    _rule(
        "L26-LNX-SSH-001",
        "SSH authentication baseline is hardened",
        "linux",
        "high",
        ("NIST_SP_800_53:AC-17", "NIST_SP_800_53:IA-2", "CMS_ARS:AC-17", "CMS_ARS:IA-2"),
        ("/etc/ssh/sshd_config", "sshd -T"),
        "Disable root SSH login, avoid empty passwords, and scope SSH access with users or groups where practical.",
    ),
    _rule(
        "L26-LNX-SSH-002",
        "SSH brute-force and idle-session limits are configured",
        "linux",
        "medium",
        ("NIST_SP_800_53:AC-7", "NIST_SP_800_53:AC-12", "CMS_ARS:AC-7", "CMS_ARS:AC-12"),
        ("/etc/ssh/sshd_config",),
        "Set MaxAuthTries, LoginGraceTime, and ClientAlive* idle timeout values to approved production limits.",
    ),
    _rule(
        "L26-LNX-PAM-001",
        "Password quality and lifetime policy is configured",
        "linux",
        "medium",
        ("NIST_SP_800_53:IA-5", "NIST_SP_800_53:CM-6", "CMS_ARS:IA-5", "CMS_ARS:CM-6"),
        ("/etc/security/pwquality.conf", "/etc/login.defs", "/etc/pam.d/*"),
        "Configure approved password quality, hashing, age, and reuse controls or document centralized identity exceptions.",
    ),
    _rule(
        "L26-LNX-AUTH-001",
        "Privileged sudo access is auditable and least-privileged",
        "linux",
        "high",
        ("NIST_SP_800_53:AC-6", "NIST_SP_800_53:AU-12", "CMS_ARS:AC-6", "CMS_ARS:AU-12"),
        ("/etc/sudoers", "/etc/sudoers.d/*"),
        "Enable sudo logging/use_pty, avoid broad NOPASSWD entries, and use named groups for privileged access.",
    ),
    _rule(
        "L26-LNX-LOG-001",
        "Audit service and audit rules are present",
        "linux",
        "medium",
        ("NIST_SP_800_53:AU-2", "NIST_SP_800_53:AU-12", "CMS_ARS:AU-2", "CMS_ARS:AU-12"),
        ("/etc/audit/auditd.conf", "/etc/audit/rules.d/*.rules"),
        "Enable auditd or equivalent telemetry for identity, privilege, time, mount, and configuration changes.",
    ),
    _rule(
        "L26-LNX-CHG-001",
        "Change-control evidence bundle is generated",
        "linux",
        "low",
        ("NIST_SP_800_53:CM-3", "NIST_SP_800_53:CM-8", "CMS_ARS:CM-3", "CMS_ARS:CM-8"),
        ("Local-81 compliance artifacts", "package manager history", "audit logs"),
        "Retain timestamped inventory, compliance, and hardening-plan artifacts with ticket and approver metadata when available.",
    ),
    _rule(
        "WEB_TLS_PROTOCOLS_MIN_12",
        "Web TLS protocols are TLS 1.2 or newer",
        "web",
        "high",
        ("NIST_SP_800_53:SC-8", "NIST_SP_800_53:SC-13", "CMS_ARS:SC-8", "CMS_ARS:SC-13"),
        ("Apache SSLProtocol", "Nginx ssl_protocols", "Tomcat Connector TLS attributes"),
        "Disable SSLv2, SSLv3, TLS 1.0, and TLS 1.1; allow TLS 1.2 and TLS 1.3 only unless TLS terminates upstream.",
    ),
    _rule(
        "WEB_TLS_WEAK_CIPHERS_DISABLED",
        "Weak web TLS ciphers are disabled",
        "web",
        "high",
        ("NIST_SP_800_53:SC-8", "NIST_SP_800_53:SC-13", "CMS_ARS:SC-8", "CMS_ARS:SC-13"),
        ("Apache SSLCipherSuite", "Nginx ssl_ciphers", "Tomcat ciphers"),
        "Remove NULL, EXPORT, DES, 3DES, RC4, MD5, anonymous, and other weak cipher suites.",
    ),
    _rule(
        "WEB_HSTS_ENABLED",
        "HTTP Strict Transport Security is enabled",
        "web",
        "medium",
        ("NIST_SP_800_53:SC-8", "NIST_SP_800_53:SC-23", "CMS_ARS:SC-8", "CMS_ARS:SC-23"),
        ("Apache Header directives", "Nginx add_header directives"),
        "Set Strict-Transport-Security with an approved max-age on HTTPS sites after validating subdomain impact.",
    ),
    _rule(
        "WEB_SECURITY_HEADERS_PRESENT",
        "Common browser security headers are configured",
        "web",
        "medium",
        ("NIST_SP_800_53:SI-10", "NIST_SP_800_53:SC-7", "CMS_ARS:SI-10", "CMS_ARS:SC-7"),
        ("Apache Header directives", "Nginx add_header directives", "hosting config"),
        "Configure X-Content-Type-Options, frame protection or CSP frame-ancestors, CSP, Referrer-Policy, and Permissions-Policy.",
    ),
    _rule(
        "APACHE_TRACE_DISABLED",
        "Apache TRACE method is disabled",
        "web",
        "medium",
        ("NIST_SP_800_53:CM-7", "NIST_SP_800_53:SC-7", "CMS_ARS:CM-7", "CMS_ARS:SC-7"),
        ("Apache TraceEnable",),
        "Set TraceEnable Off globally.",
    ),
    _rule(
        "WEB_SERVER_TOKENS_MINIMIZED",
        "Web server version banners are minimized",
        "web",
        "low",
        ("NIST_SP_800_53:SC-7", "NIST_SP_800_53:CM-6", "CMS_ARS:SC-7", "CMS_ARS:CM-6"),
        ("Apache ServerTokens/ServerSignature", "Nginx server_tokens"),
        "Suppress detailed server version banners where supported.",
    ),
    _rule(
        "WEB_ACCESS_ERROR_LOGGING_ENABLED",
        "Web access and error logging is enabled",
        "web",
        "medium",
        ("NIST_SP_800_53:AU-2", "NIST_SP_800_53:AU-12", "CMS_ARS:AU-2", "CMS_ARS:AU-12"),
        ("Apache CustomLog/ErrorLog", "Nginx access_log/error_log", "Tomcat AccessLogValve"),
        "Enable access and error logs, protect them, and retain them according to policy.",
    ),
    _rule(
        "WEB_TIMEOUTS_CONFIGURED",
        "Web request timeout limits are configured",
        "web",
        "medium",
        ("NIST_SP_800_53:SC-5", "NIST_SP_800_53:SC-7", "CMS_ARS:SC-5", "CMS_ARS:SC-7"),
        ("Apache Timeout/KeepAliveTimeout/RequestReadTimeout", "Nginx timeout directives"),
        "Set finite conservative timeouts to reduce resource-exhaustion exposure.",
    ),
    _rule(
        "JVM_REMOTE_DEBUG_DISABLED",
        "JVM remote debug is disabled in production",
        "java",
        "high",
        ("NIST_SP_800_53:AC-3", "NIST_SP_800_53:CM-7", "CMS_ARS:AC-3", "CMS_ARS:CM-7"),
        ("JAVA_OPTS", "CATALINA_OPTS", "systemd units", "Dockerfiles"),
        "Remove JDWP remote debug listeners in production or bind temporary debug access to localhost only.",
    ),
    _rule(
        "JVM_JMX_SECURED",
        "JMX remote management requires authentication and TLS",
        "java",
        "high",
        ("NIST_SP_800_53:AC-3", "NIST_SP_800_53:IA-2", "CMS_ARS:AC-3", "CMS_ARS:IA-2"),
        ("JAVA_OPTS", "CATALINA_OPTS", "systemd units"),
        "Require authenticated and encrypted JMX, or expose it only through a protected local tunnel.",
    ),
    _rule(
        "TOMCAT_SHUTDOWN_PORT_DISABLED",
        "Tomcat shutdown port is disabled",
        "java",
        "medium",
        ("NIST_SP_800_53:CM-7", "NIST_SP_800_53:SC-7", "CMS_ARS:CM-7", "CMS_ARS:SC-7"),
        ("Tomcat server.xml",),
        "Set the Tomcat Server shutdown port to -1 unless a protected operational requirement exists.",
    ),
    _rule(
        "TOMCAT_MANAGER_DEFAULT_APPS_RESTRICTED",
        "Tomcat manager and default applications are removed or restricted",
        "java",
        "high",
        ("NIST_SP_800_53:AC-3", "NIST_SP_800_53:CM-7", "CMS_ARS:AC-3", "CMS_ARS:CM-7"),
        ("Tomcat webapps", "tomcat-users.xml", "manager context files"),
        "Remove default apps or restrict manager applications to approved admin networks with strong credentials.",
    ),
    _rule(
        "L26-JS-002",
        "Node package lockfile is present",
        "javascript",
        "medium",
        ("NIST_SP_800_53:CM-2", "NIST_SP_800_53:SA-10", "CMS_ARS:CM-2", "CMS_ARS:SA-10"),
        ("package.json", "package-lock.json", "yarn.lock", "pnpm-lock.yaml"),
        "Commit exactly one package lockfile for reproducible dependency resolution.",
    ),
    _rule(
        "L26-JS-004",
        "Node runtime and package manager versions are pinned",
        "javascript",
        "medium",
        ("NIST_SP_800_53:CM-6", "NIST_SP_800_53:SA-10", "CMS_ARS:CM-6", "CMS_ARS:SA-10"),
        ("package.json engines", "packageManager"),
        "Set engines.node and packageManager to approved, versioned values.",
    ),
    _rule(
        "L26-JS-006",
        "Node lifecycle scripts are reviewed",
        "javascript",
        "medium",
        ("NIST_SP_800_53:CM-7", "NIST_SP_800_53:SA-11", "CMS_ARS:CM-7", "CMS_ARS:SA-11"),
        ("package.json scripts",),
        "Review install/prepare/prepublish lifecycle scripts and document legitimate build requirements.",
    ),
    _rule(
        "L26-JS-007",
        "Package scripts do not run remote shell code",
        "javascript",
        "high",
        ("NIST_SP_800_53:CM-7", "NIST_SP_800_53:SI-10", "CMS_ARS:CM-7", "CMS_ARS:SI-10"),
        ("package.json scripts",),
        "Replace curl/wget-to-shell, remote npx execution, and similar patterns with pinned reviewed tooling.",
    ),
    _rule(
        "L26-JS-011",
        "npm registry configuration uses secure transport",
        "javascript",
        "high",
        ("NIST_SP_800_53:SC-8", "NIST_SP_800_53:SC-13", "CMS_ARS:SC-8", "CMS_ARS:SC-13"),
        (".npmrc",),
        "Use HTTPS registries and strict SSL validation.",
    ),
    _rule(
        "L26-JS-012",
        "npm credentials are not committed",
        "javascript",
        "critical",
        ("NIST_SP_800_53:IA-5", "NIST_SP_800_53:SC-28", "CMS_ARS:IA-5", "CMS_ARS:SC-28"),
        (".npmrc",),
        "Remove committed tokens and load registry credentials from protected environment or secret-manager references.",
    ),
    _rule(
        "L26-NODE-001",
        "Node environment files do not contain literal secrets",
        "javascript",
        "high",
        ("NIST_SP_800_53:IA-5", "NIST_SP_800_53:SC-28", "CMS_ARS:IA-5", "CMS_ARS:SC-28"),
        (".env*", "config*.json", "environment files"),
        "Move secrets out of source-controlled environment/config files into secret references.",
    ),
    _rule(
        "L26-NODE-002",
        "Unsafe Node runtime flags are not used",
        "javascript",
        "high",
        ("NIST_SP_800_53:CM-6", "NIST_SP_800_53:SC-8", "CMS_ARS:CM-6", "CMS_ARS:SC-8"),
        ("package.json scripts", "systemd units", "Dockerfiles"),
        "Remove NODE_TLS_REJECT_UNAUTHORIZED=0, wildcard inspector listeners, and legacy OpenSSL flags from production paths.",
    ),
    _rule(
        "L26-NG-002",
        "Angular production optimization is enabled",
        "angular",
        "medium",
        ("NIST_SP_800_53:CM-6", "NIST_SP_800_53:SA-11", "CMS_ARS:CM-6", "CMS_ARS:SA-11"),
        ("angular.json production configuration",),
        "Enable production optimization, AOT, and build optimizer where supported.",
    ),
    _rule(
        "L26-NG-003",
        "Angular production source maps are disabled",
        "angular",
        "high",
        ("NIST_SP_800_53:SC-28", "NIST_SP_800_53:SI-11", "CMS_ARS:SC-28", "CMS_ARS:SI-11"),
        ("angular.json production configuration",),
        "Disable production source maps unless protected by an approved private artifact workflow.",
    ),
    _rule(
        "L26-NG-009",
        "Risky Angular DOM trust bypasses are reviewed",
        "angular",
        "high",
        ("NIST_SP_800_53:SA-11", "NIST_SP_800_53:SI-10", "CMS_ARS:SA-11", "CMS_ARS:SI-10"),
        ("*.ts", "*.html"),
        "Review DomSanitizer bypassSecurityTrust* and direct innerHTML patterns with exact evidence.",
    ),
)


def rules_by_id() -> dict[str, ComplianceRule]:
    return {rule.rule_id: rule for rule in RULES}


def get_rule(rule_id: str) -> ComplianceRule:
    return rules_by_id()[rule_id]


def rules_for_category(category: str) -> list[ComplianceRule]:
    return [rule for rule in RULES if rule.category == category]
