[seraf]
project = seraf

[defaults]
rsync_opts = -az
backup = true
backup_suffix = .bkp
remote_mkdir = true

[routing]
env_from_filename_prefix = s:sys,q:qa,p:production
env_from_server_name_char_at = 4
env_from_server_name_char_map = s:sys,q:qa,p:production

# Add one or more scope sections, for example:
# [scope "app"]
# enabled = true
# source_dir = /srv/seraf/source
# target_dir = /srv/seraf/target
# servers = app01.example.com,app02.example.com
# discovery = mtime_since_last_success
